argo-cd:
  configs:
    params:
      server.insecure: true
    cm:
      oidc.config: |
        name: Keycloak
        issuer: $oidc.keycloak.issuer
        clientID: $oidc.keycloak.clientID
        clientSecret: $oidc.keycloak.clientSecret
        requestedScopes: ["openid", "profile", "email"]
      policy.csv: |
        g, /ArgoCD/Admin, role:admin

  global:
    domain: argo.lan

  server:
    httproute:
      enabled: true
      hostnames:
        - argo.lan
      parentRefs:
        - name: traefik-gateway
          namespace: traefik
          group: gateway.networking.k8s.io	
          kind: Gateway
  
  secret:
    createSecret: false
  
  extraObjects:
    - apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      metadata:
        name: argocd-secret
        namespace: argocd
      spec:
        secretStoreRef:
          kind: ClusterSecretStore
          name: infisical

        target:
          name: argocd-secret
          creationPolicy: "Merge"

        data:
          - secretKey: oidc.keycloak.issuer
            remoteRef:
              key: /argocd/OIDC_ISSUER
          - secretKey: oidc.keycloak.clientID
            remoteRef:
              key: /argocd/OIDC_CLIENT_ID
          - secretKey: oidc.keycloak.clientSecret
            remoteRef:
              key: /argocd/OIDC_CLIENT_SECRET