argo-cd:
  configs:
    params:
      server.insecure: true
    cm:
      oidc.config: |
        name: Keycloak
        issuer: $OIDC_ISSUER
        clientID: $OIDC_CLIENT_ID
        clientSecret: $OIDC_CLIENT_SECRET
        requestedScopes: ["openid", "profile", "email", "groups"]

  global:
    domain: argo.lan

  server:
    httproute:
      enabled: true
      hostnames:
        - argo.lan
      parentRefs:
        - name: traefik-gateway
          namespace: traefik
          group: gateway.networking.k8s.io	
          kind: Gateway
  
  secret:
    createSecret: false
  
  extraObjects:
    - apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      metadata:
        name: argocd-secret
        namespace: argocd
      spec:
        secretStoreRef:
          kind: ClusterSecretStore
          name: infisical

        target:
          name: argocd-secret-new

        dataFrom:
          - extract:
              key: /argocd/