apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agentgateway
  finalizers:
  - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 4.6.2
    helm:
      releaseName: agentgateway
      valuesObject:
        controllers:
          agentgateway:
            strategy: RollingUpdate
            containers:
              app:
                image:
                  repository: ghcr.io/agentgateway/agentgateway
                  tag: latest
                  pullPolicy: IfNotPresent
                env:
                  ADMIN_ADDR: "0.0.0.0:15000"
                  LOCAL_XDS_PATH: "/config/config.yaml"

        configMaps:
          agw-config:
            enabled: true
            data:
              config.yaml: |
                # yaml-language-server: $schema=https://agentgateway.dev/schema/config
                binds:
                  - port: 3000
                    listeners:
                      - protocol: HTTP
                        routes:
                          - name: direct-response
                            matches:
                              - path:
                                  pathPrefix: /
                            policies:
                              directResponse:
                                body: "agentgateway standalone is running"
                                status: 200

        persistence:
          config:
            enabled: true
            type: configMap
            identifier: agw-config
            globalMounts:
              - path: /config/config.yaml
                subPath: config.yaml
                readOnly: true

        service:
          app:
            controller: agentgateway
            ports:
              http:
                port: 15000
  destination:
    server: https://kubernetes.default.svc
    namespace: agentgateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
