apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agentgateway
  finalizers:
  - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 4.6.2
    helm:
      releaseName: agentgateway
      valuesObject:
        controllers:
          agentgateway:
            strategy: RollingUpdate
            containers:
              app:
                image:
                  repository: ghcr.io/agentgateway/agentgateway
                  tag: latest
                  pullPolicy: IfNotPresent
                env:
                  ADMIN_ADDR: "0.0.0.0:15000"
                probes:
                  liveness:
                    enabled: true
                    custom: true
                    spec:
                      httpGet:
                        path: /ready
                        port: 15021
                      initialDelaySeconds: 5
                      periodSeconds: 10
                  readiness:
                    enabled: true
                    custom: true
                    spec:
                      httpGet:
                        path: /ready
                        port: 15021
                      initialDelaySeconds: 3
                      periodSeconds: 10

        service:
          app:
            controller: agentgateway
            ports:
              http:
                port: 15000
  destination:
    server: https://kubernetes.default.svc
    namespace: agentgateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
