apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agentgateway
  finalizers:
  - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    repoURL: oci://cr.agentgateway.dev/charts
    chart: agentgateway
    targetRevision: v1.0.1
    helm:
      releaseName: agentgateway
      valuesObject:
        controller:
          replicaCount: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: agentgateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
