apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kestra
spec:
  project: default

  source:
    repoURL: https://helm.kestra.io/
    chart: kestra
    targetRevision: 1.0.31
    helm:
      valuesObject:
        common:
          extraEnvFrom:
            - secretRef:
                name: kestra-pg-user
                namespace: db
            - secretRef:
                name: kestra-s3-credentials
        configurations:
          application:
            datasources:
              postgres:
                url: jdbc:postgresql://postgres-rw.db.svc.cluster.local:5432/kestra
                driver-class-name: org.postgresql.Driver
                username: ${POSTGRES_USER}
                password: ${POSTGRES_PASSWORD}
                maximum-pool-size: 20
                minimum-idle: 10
            kestra:
              anonymous-usage-report:
                enabled: false
              ui-anonymous-usage-report:
                enabled: false
              queue:
                type: postgres
              repository:
                type: postgres
              storage:
                type: minio
                minio:
                  endpoint: http://minio-svc.minio.svc.cluster.local
                  port: 9000
                  bucket: kestra
                  accessKey: ${S3_ACCESS_KEY}
                  secretKey: ${S3_SECRET_KEY}
        ingress:
          enabled: true
          hosts:
            - host: kestra.lan
              paths:
                - path: /
                  pathType: Prefix
            - host: kestra.vcov.org
              paths:
                - path: /
                  pathType: Prefix
        extraManifests:
          - apiVersion: postgresql.cnpg.io/v1
            kind: Database
            metadata:
              name: kestra-db
              namespace: db
            spec:
              name: kestra
              owner: kestra
              cluster:
                name: postgres
              extensions:
                - name: bloom
                  ensure: present
          - apiVersion: external-secrets.io/v1
            kind: ExternalSecret
            metadata:
              name: kestra-pg-user
              namespace: db
            spec:
              secretStoreRef:
                kind: ClusterSecretStore
                name: infisical

              target:
                name: kestra-pg-user

              data:
                - secretKey: POSTGRES_USER
                  remoteRef:
                    key: /kestra/PG_USER

                - secretKey: POSTGRES_PASSWORD
                  remoteRef:
                    key: /kestra/PG_PASSWORD
          - apiVersion: external-secrets.io/v1
            kind: ExternalSecret
            metadata:
              name: kestra-s3-credentials
              namespace: kestra
            spec:
              secretStoreRef:
                kind: ClusterSecretStore
                name: infisical

              target:
                name: kestra-s3-credentials

              data:
                - secretKey: S3_ACCESS_KEY
                  remoteRef:
                    key: /kestra/S3_ACCESS_KEY
                - secretKey: S3_SECRET_KEY
                  remoteRef:
                    key: /kestra/S3_SECRET_KEY
  destination:
    server: https://kubernetes.default.svc
    namespace: kestra

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true