apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  finalizers:
  - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/codecentric/helm-charts/keycloakx
    chart: keycloak
    targetRevision: 7.1.8
    helm:
      valuesObject:
        replicas: 2

        postgresql:
          enabled: false
        
        dbchecker:
          enabled: true
        
        database:
          vendor: postgres
          hostname: postgres-rw.db.svc.cluster.local
          port: 5432
          database: keycloak
          username: keycloak
          existingSecret: keycloak

        httpRoute:
          enabled: true
          parentRefs:
            - name: traefik-gateway
              namespace: traefik
              sectionName: https
          hostnames:
            - sso.lan
        
        extraEnv: |
          - name: KC_PROXY
            value: "passthrough"
          - name: KEYCLOAK_ADMIN
            valueFrom:
              secretKeyRef:
                name: keycloak
                key: KEYCLOAK_USER
          - name: KEYCLOAK_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak
                key: KEYCLOAK_PASSWORD
        
        extraManifests:
          - |
            apiVersion: postgresql.cnpg.io/v1
            kind: Database
            metadata:
              name: keycloak-db
              namespace: db
            spec:
              name: keycloak
              owner: keycloak
              cluster:
                name: postgres
              extensions:
                - name: bloom
                  ensure: present
          - |
            apiVersion: external-secrets.io/v1
            kind: ExternalSecret
            metadata:
              name: keycloak-password
              namespace: db
            spec:
              secretStoreRef:
                kind: ClusterSecretStore
                name: infisical

              target:
                name: keycloak-password

              data:
                - secretKey: username
                  remoteRef:
                    key: /keycloak/PG_USER

                - secretKey: password
                  remoteRef:
                    key: /keycloak/PG_PASSWORD
          - |
            apiVersion: external-secrets.io/v1
            kind: ExternalSecret
            metadata:
              name: keycloak-env
              namespace: tooling
            spec:
              secretStoreRef:
                kind: ClusterSecretStore
                name: infisical

              target:
                name: keycloak

              data:
                - secretKey: password
                  remoteRef:
                    key: /keycloak/PG_PASSWORD
                - secretKey: KEYCLOAK_USER
                  remoteRef:
                    key: /keycloak/KEYCLOAK_USER
                - secretKey: KEYCLOAK_PASSWORD
                  remoteRef:
                    key: /keycloak/KEYCLOAK_PASSWORD
  destination:
    server: https://kubernetes.default.svc
    namespace: tooling
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true