apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  finalizers:
  - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/codecentric/helm-charts/keycloak
    chart: keycloak
    targetRevision: 18.10.0
    helm:
      valuesObject:
        replicaCount: 2

        postgresql:
          enabled: false
        
        ingress:
          enabled: true
          ingressClassName: traefik
          rules:
            - host: keycloak.vcov.org
              paths:
                - path: /
                  pathType: Prefix
        
        extraEnv: |
          - name: DB_VENDOR
            value: postgres
          - name: DB_ADDR
            value: postgres-rw.svc.cluster.local
          - name: DB_PORT
            value: "5432"
          - name: DB_DATABASE
            value: keycloak
          - name: JGROUPS_DISCOVERY_PROTOCOL
            value: kubernetes.KUBE_PING
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: CACHE_OWNERS_COUNT
            value: "2"
          - name: CACHE_OWNERS_AUTH_SESSIONS_COUNT
            value: "2"
          - name: PROXY_ADDRESS_FORWARDING
            value: "true"

        extraEnvFrom: |
          - secretRef:
              name: 'keycloak-env'
        
        rbac:
          create: true
          rules:
            - apiGroups:
                - ""
              resources:
                - pods
              verbs:
                - get
                - list
  destination:
    server: https://kubernetes.default.svc
    namespace: tooling
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: keycloak-db
  namespace: db
spec:
  name: keycloak
  owner: keycloak
  cluster:
    name: postgres
  extensions:
    - name: bloom
      ensure: present
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-password
  namespace: db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: keycloak-password

  data:
    - secretKey: username
      remoteRef:
        key: /keycloak/PG_USER

    - secretKey: password
      remoteRef:
        key: /keycloak/PG_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-env
  namespace: tooling
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: keycloak-env

  data:
    - secretKey: DB_USER
      remoteRef:
        key: /keycloak/PG_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: /keycloak/PG_PASSWORD
    - secretKey: KEYCLOAK_USER
      remoteRef:
        key: /keycloak/KEYCLOAK_USER
    - secretKey: KEYCLOAK_PASSWORD
      remoteRef:
        key: /keycloak/KEYCLOAK_PASSWORD