apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matter-server
  finalizers:
  - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default

  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 4.6.2
    helm:
      releaseName: matter-server
      valuesObject:
        controllers:
          matter-server:
            strategy: RollingUpdate
            containers:
              app:
                image:
                  repository: ghcr.io/home-assistant-libs/python-matter-server
                  tag: stable
                  pullPolicy: IfNotPresent
                args:
                  - --storage-path
                  - /data
                  - --paa-root-cert-dir
                  - /data/credentials
                  - --port
                  - "5580"

        service:
          app:
            controller: matter-server
            ports:
              http:
                port: 5580

        persistence:
          data:
            enabled: true
            type: persistentVolumeClaim
            accessMode: ReadWriteOnce
            size: 2Gi
            storageClass: local-path
            globalMounts:
              - path: /data

  destination:
    server: https://kubernetes.default.svc
    namespace: smathome

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
