apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media
  finalizers:
  - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: 4.6.2
    helm:
      valuesObject:
        serviceAccount:
          default:
            enabled: true
        rbac:
          roles:
            manage-endpointslices:
              forceRename: manage-endpointslices
              type: Role
              rules:
                - apiGroups: ["discovery.k8s.io"]
                  resources: ["endpointslices"]
                  verbs: ["get", "list", "create", "update", "patch"]
          bindings:
            manage-endpointslices-binding:
              forceRename: allow-job-to-manage-endpointslices
              type: RoleBinding
              roleRef:
                identifier: manage-endpointslices
              subjects:
                - identifier: default
        controllers:
          # media:
          #   enabled: true
          #   type: statefulset
          #   replicas: 0
          #   containers:
          #     dummy:
          #       image:
          #         repository: nginx
          #         tag: latest
          endpoint-config:
            enabled: true
            type: job
            job:
              backoffLimit: 1
            serviceAccount:
              identifier: default
            containers:
              main:
                image:
                  repository: alpine/kubectl
                  tag: 1.35.0
                command:
                  - /bin/sh
                  - -c
                  - |
                    cat <<'EOF' | kubectl apply -f -
                    apiVersion: discovery.k8s.io/v1
                    kind: EndpointSlice
                    metadata:
                      name: truenas
                      namespace: media
                      labels:
                        kubernetes.io/service-name: media
                    addressType: IPv4
                    ports:
                      - name: jellyfin
                        protocol: TCP
                        port: 30013
                    endpoints:
                      - conditions:
                          ready: true
                        addresses:
                        - 192.168.1.10
                    EOF
        service:
          truenas:
            controller: endpoint-config
            ports:
              jellyfin: 
                port: 30013
        route:
          jellyfin:
            enabled: true
            hostnames:
              - jellyfin2.vcov.org
            parentRefs:
              - name: traefik-gateway
                namespace: traefik
            rules: 
            -  backendRefs:
                - name: media
                  port: 30013
        # ingress:
        #   media:
        #     hosts:
        #       - host: jellyfin2.vcov.org
        #         paths:
        #           - path: /
        #             pathType: Prefix
        #             service:
        #               identifier: truenas
        #               port: 30013
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
# ---
# apiVersion: discovery.k8s.io/v1
# kind: EndpointSlice
# metadata:
#   name: truenas
#   namespace: media
#   labels:
#     kubernetes.io/service-name: media
# addressType: IPv4
# ports:
#   - name: jellyfin
#     port: 30013
# endpoints:
#   - addresses:
#     - 192.168.1.10