apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
spec:
  project: default

  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: n8n
    targetRevision: 1.16.29
    helm:
      valuesObject:
        fullnameOverride: n8n
        image:
          tag: 2.11.2
        log:
          level: warn

        db:
          type: postgresdb
        
        existingEncryptionKeySecret: n8n

        externalPostgresql:
          host: "postgres-rw.db"
          username: "n8n"
          database: "n8n"
          existingSecret: n8n
        
        timezone: "Europe/Tallinn"

        main:
          extraSecretNamesForEnvFrom:
            - n8n
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 512m
              memory: 512Mi

        worker:
          mode: queue

          autoscaling:
            enabled: true

          waitMainNodeReady:
            enabled: true
          
          extraSecretNamesForEnvFrom:
            - n8n

          resources:
            requests:
              cpu: 1000m
              memory: 250Mi
            limits:
              cpu: 2000m
              memory: 2Gi

        redis:
          enabled: true

        webhook:
          mode: queue

          autoscaling:
            enabled: true

          waitMainNodeReady:
            enabled: true
          
          extraSecretNamesForEnvFrom:
            - n8n

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 512m
              memory: 512Mi        
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: n8n-db
  namespace: db
spec:
  name: n8n
  owner: n8n
  cluster:
    name: postgres
  extensions:
    - name: bloom
      ensure: present
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-password
  namespace: db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: n8n-password

  data:
    - secretKey: username
      remoteRef:
        key: /n8n/PG_USER
    - secretKey: password
      remoteRef:
        key: /n8n/PG_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-secrets
  namespace: n8n
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: n8n

  data:
    - secretKey: N8N_EDITOR_BASE_URL
      remoteRef:
        key: /n8n/N8N_HOST
    # - secretKey: WEBHOOK_URL
    #   remoteRef:
    #     key: /n8n/N8N_WEBHOOK_URL
    - secretKey: N8N_ENCRYPTION_KEY
      remoteRef:
        key: /n8n/N8N_ENCRYPTION_KEY
    - secretKey: postgres-password
      remoteRef:
        key: /n8n/PG_PASSWORD