apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: newt
  finalizers:
  - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    repoURL: https://charts.fossorial.io
    chart: fossorial
    # helm:
    #   values: |
    #     pushgateway:
    #       enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: pangolin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true