apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgadmin
  finalizers:
  - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    repoURL: https://helm.runix.net
    chart: pgadmin4
    targetRevision: 1.57.0
    helm:
      valuesObject:
        envVarsExtra:
          - name: POSTGRES_DEFAULT_EMAIL
            valueFrom:
              secretKeyRef:
                name: pgadmin-credentials
                key: POSTGRES_DEFAULT_EMAIL
          - name: POSTGRES_DEFAULT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pgadmin-credentials
                key: POSTGRES_DEFAULT_PASSWORD

        serverDefinitions:
          enabled: true
          servers:
            local:
              Name: Local Postgres
              Group: Servers
              Host: postgres-rw

        httpRoute:
          enabled: true
          hostnames:
            - pgadmin.lan
          parentRefs:
            - name: traefik-gateway
              namespace: traefik
        
        persistentVolume:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: db
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin-credentials
  namespace: db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: pgadmin-credentials

  data:
    - secretKey: PGADMIN_DEFAULT_EMAIL
      remoteRef:
        key: /pgadmin/PGADMIN_DEFAULT_EMAIL

    - secretKey: PGADMIN_DEFAULT_PASSWORD
      remoteRef:
        key: /pgadmin/PGADMIN_DEFAULT_PASSWORD