apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-operator
  finalizers:
  - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    repoURL: https://cloudnative-pg.github.io/charts
    chart: cloudnative-pg
    targetRevision: 0.27.0
    helm:
      valuesObject:
        config:
          clusterWide: true
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  finalizers:
  - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    repoURL: https://cloudnative-pg.github.io/charts
    chart: cluster
    targetRevision: 0.5.0
    helm:
      valuesObject:
        nameOverride: postgres
        cluster:
          instances: 2

          storage:
            size: 20Gi
            storageClass: local-path

          enableSuperuserAccess: true
        
          roles:
            - name: linkwarden
              ensure: present
              login: true
              passwordSecret:
                name: linkwarden-pg-user
            - name: obico
              ensure: present
              login: true
              passwordSecret:
                name: obico-pg-user
  destination:
    server: https://kubernetes.default.svc
    namespace: db
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true