apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-operator
  finalizers:
  - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    repoURL: https://cloudnative-pg.github.io/charts
    chart: cloudnative-pg
    targetRevision: 0.27.0
    helm:
      valuesObject:
        config:
          clusterWide: true
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-rw-lb
  namespace: db
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.165
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres
    cnpg.io/instanceRole: primary
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-password
  namespace: db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: litellm-password
  data:
    - secretKey: username
      remoteRef:
        key: /litellm/PG_USER
    - secretKey: password
      remoteRef:
        key: /litellm/PG_PASSWORD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  finalizers:
  - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    repoURL: https://cloudnative-pg.github.io/charts
    chart: cluster
    targetRevision: 0.5.0
    helm:
      valuesObject:
        nameOverride: postgres
        cluster:
          instances: 2

          storage:
            size: 20Gi
            storageClass: local-path

          enableSuperuserAccess: true
        
          roles:
            - name: umami
              ensure: present
              login: true
              passwordSecret:
                name: umami-password
            - name: sparky
              ensure: present
              login: true
              passwordSecret:
                name: sparky-password
            - name: keycloak
              ensure: present
              login: true
              passwordSecret:
                name: keycloak-password
            - name: terrakube
              ensure: present
              login: true
              passwordSecret:
                name: terrakube-password
            - name: n8n
              ensure: present
              login: true
              passwordSecret:
                name: n8n-password
            - name: contextforge
              ensure: present
              login: true
              passwordSecret:
                name: context-forge-password
            - name: litellm
              ensure: present
              login: true
              passwordSecret:
                name: litellm-password
            - name: bifrost
              ensure: present
              login: true
              passwordSecret:
                name: bifrost-password
            - name: phoenix
              ensure: present
              login: true
              passwordSecret:
                name: phoenix-password
            - name: instatic
              ensure: present
              login: true
              passwordSecret:
                name: instatic-password
            - name: buzz
              ensure: present
              login: true
              passwordSecret:
                name: buzz-password
  destination:
    server: https://kubernetes.default.svc
    namespace: db
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
