apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terrakube
spec:
  project: default

  source:
    repoURL: https://terrakube-io.github.io/terrakube-helm-chart
    chart: terrakube
    targetRevision: 4.5.5
    helm:
      valuesObject:
        security:
          useOpenLDAP: false
        dex:
          enabled: true
          existingSecret: true
        api:
          existingSecret: true
          defaultDatabase: false
          defaultRedis: true
          version: "2.30.0-beta.5"
        executor:
          enabled: true
          existingSecret: true
          version: "2.30.0-beta.5"
        registry:
          enabled: true
          existingSecret: true
          version: "2.30.0-beta.5"
        ui:
          enabled: true
          existingSecret: true
          version: "2.30.0-beta.5"
        ingress:
          controller: "gatewayapi"
          gatewayapi:
            enabled: true
            gateways:
              - name: traefik-gateway
                namespace: traefik
                sectionName: websecure
          ui:
            enabled: true
            domain: "terrakube.vcov.org"
            path: "/"
            pathType: "Prefix"
            useTls: false
          api:
            enabled: true
            domain: "terrakube.vcov.org"
            path: "/api"
            pathType: "Prefix"
            useTls: false
          registry:
            enabled: false
          dex:
            enabled: true
            domain: "terrakube.vcov.org"
            path: "/dex"
            pathType: "Prefix"
            useTls: false
          executor:
            enabled: false
        storage:
          defaultStorage: false
        
  destination:
    server: https://kubernetes.default.svc
    namespace: terrakube

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: terrakube-db
  namespace: db
spec:
  name: terrakube
  owner: terrakube
  cluster:
    name: postgres
  extensions:
    - name: bloom
      ensure: present
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: terrakube-password
  namespace: db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: terrakube-password

  data:
    - secretKey: username
      remoteRef:
        key: /terrakube/PG_USER
    - secretKey: password
      remoteRef:
        key: /terrakube/PG_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: terrakube-api-config
  namespace: terrakube
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: terrakube-api-secrets

  dataFrom:
    - extract:
        key: /terrakube/API_CFG
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: terrakube-ui-config
  namespace: terrakube
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: terrakube-ui-secrets

  data:
    - secretKey: env-config.js
      remoteRef:
        key: /terrakube/UI_CFG
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: terrakube-dex-config
  namespace: terrakube
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: terrakube-dex

  data:
    - secretKey: config.yaml
      remoteRef:
        key: /terrakube/DEX_CFG
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: terrakube-executor-config
  namespace: terrakube
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: terrakube-executor-secrets

  dataFrom:
    - extract:
        key: /terrakube/EXECUTOR_CFG
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: terrakube-registry-config
  namespace: terrakube
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: terrakube-registry-secrets

  dataFrom:
    - extract:
        key: /terrakube/REGISTRY_CFG