apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  finalizers:
  - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    repoURL: https://github.com/hashicorp/vault-helm.git
    path: .
    targetRevision: v0.32.0
    helm:
      valuesObject:
        global:
          enabled: false
        
        server:
          enabled: true

          ingress:
            enabled: true
            ingressClassName: traefik
            activeService: true
            hosts:
              - host: vault.lan

          dataStorage:
            enabled: false

          ha:
            enabled: true
            replicas: 2

            config: |
              ui = true

              listener "tcp" {
                tls_disable = 1
                address = "[::]:8200"
                cluster_address = "[::]:8201"
              }

              storage "s3" {
                endpoint = "minio-svc.minio.svc.cluster.local:9000"
                s3_force_path_style = true
                bucket = "vault"
                region = "home"
              }

              service_registration "kubernetes" {}

          extraSecretEnvironmentVars:
            - envName: AWS_ACCESS_KEY_ID
              secretName: vault-env
              secretKey: MINIO_ACCESS_KEY
            - envName: AWS_SECRET_ACCESS_KEY
              secretName: vault-env
              secretKey: MINIO_SECRET_KEY

        ui:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: tooling
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-env
  namespace: tooling
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: vault-env

  data:
    - secretKey: MINIO_ACCESS_KEY
      remoteRef:
        key: /vault/MINIO_ACCESS_KEY
    - secretKey: MINIO_SECRET_KEY
      remoteRef:
        key: /vault/MINIO_SECRET_KEY